INTERNAL_SERVER_ERROR:
  message: "We have encountered an internal server error."
  developer_message: "Internal server error: {error}"

NOT_FOUND:
  message: "{resource} does not exist."

UNAUTHORIZED:
  message: "Authentication failed."
  developer_message: "Authentication failed: {error}"

UNPROCESSABLE_ENTITY:
  message: "{message}"

INVALID_DATA:
  message: "{message}"